# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#
# Developer tasks for pip-tools for the Task runner.
#
# See: https://pypi.org/project/pip-tools/
#
# yamllint disable rule:line-length

version: "3"

silent: true

vars:
  PY_DEV_REQS_TXT: "requirements-developer.txt"
  PIP_COMPILE_CMD: "pipx run --spec pip-tools pip-compile"
  PIP_SYNC_CMD: "pipx run --spec pip-tools pip-sync"

tasks:
  compile:
    desc: Compile Python requirements files
    dir: "{{ .USER_WORKING_DIR }}"
    cmds:
      - cmd: "{{.PIP_COMPILE_CMD}} -o {{ .PY_DEV_REQS_TXT }} -q --all-extras pyproject.toml"
      - cmd: "{{.PIP_COMPILE_CMD}} -o requirements.txt -q pyproject.toml"

  editable:
    desc: Install as editable to Python virtual environment
    dir: "{{ .USER_WORKING_DIR }}"
    cmds:
      - python3 -m pip install -e .

  sync:
    desc: Sync Python virtual environment with {{ .PY_DEV_REQS_TXT }}
    dir: "{{ .USER_WORKING_DIR }}"
    cmds:
      - "{{.PIP_SYNC_CMD}} {{ .PY_DEV_REQS_TXT }}"

  update-reqs:
    desc: Update Python dependencies
    internal: true
    dir: "{{ .USER_WORKING_DIR }}"
    cmds:
      - cmd: "{{.PIP_COMPILE_CMD}} -o {{ .PY_DEV_REQS_TXT }} -q -U --all-extras pyproject.toml"
      - cmd: "{{.PIP_COMPILE_CMD}} -o requirements.txt -q -U pyproject.toml"
