# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#
# Developer tasks for pip-tools for the Task runner.
#
# See: https://pypi.org/project/pip-tools/

version: "3"

silent: true

vars:
  PY_DEV_REQS_TXT: "requirements-developer.txt"
  PY_DEV_VENV: ".venv"

tasks:
  compile:
    desc: Compile Python requirements files
    dir: "{{ .USER_WORKING_DIR }}"
    cmds:
      - cmd: pip-compile -o {{ .PY_DEV_REQS_TXT }} -q --all-extras pyproject.toml
      - cmd: pip-compile -o requirements.txt -q pyproject.toml

  create:
    desc: Create Python virtual environment
    dir: "{{ .USER_WORKING_DIR }}"
    cmds:
      - python3 -m venv {{ .PY_DEV_VENV }}

  delete:
    desc: Delete Python virtual environment
    dir: "{{ .USER_WORKING_DIR }}"
    cmds:
      - rm -fr {{ .PY_DEV_VENV }}

  editable:
    desc: Install as editable to Python virtual environment
    dir: "{{ .USER_WORKING_DIR }}"
    cmds:
      - python3 -m pip install -e .

  sync:
    desc: Sync Python virtual environment with {{ .PY_DEV_REQS_TXT }}
    dir: "{{ .USER_WORKING_DIR }}"
    cmds:
      - pip-sync {{ .PY_DEV_REQS_TXT }}

  update-reqs:
    desc: Update Python dependencies
    internal: true
    dir: "{{ .USER_WORKING_DIR }}"
    cmds:
      - cmd: pip-compile -o {{ .PY_DEV_REQS_TXT }} -q -U --all-extras pyproject.toml
      - cmd: pip-compile -o requirements.txt -q -U pyproject.toml
