# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#
# Configuration for markdownlint CLI tool
#
# See https://github.com/DavidAnson/markdownlint-cli2

config:
  MD013: false
