# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#
# Configuration for pre-commit
#
# See https://pre-commit.com

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
  - repo: https://github.com/fsfe/reuse-tool
    rev: "v3.0.2"
    hooks:
      - id: reuse
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: "v0.13.0"
    hooks:
      - id: markdownlint-cli2
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.5.0"
    hooks:
      - id: ruff
        args: [--select, I, --fix, -q]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.10.0"
    hooks:
      - id: mypy
        args: [--exclude, bin]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: "0.28.4"
    hooks:
      - id: check-gitlab-ci
      - id: check-taskfile
  - repo: https://github.com/adrienverge/yamllint.git
    rev: "v1.35.1"
    hooks:
      - id: yamllint
        args: [--strict]
  - repo: local
    hooks:
      - id: trivy-config
        name: trivy config
        entry: trivy
        language: system
        args:
          [
            config,
            --cache-dir,
            tmp/trivy,
            --ignorefile,
            ./.trivyignore.yaml,
            --exit-code,
            "1",
            .,
          ]
        pass_filenames: false
      - id: trivy-fs
        name: trivy fs
        entry: trivy
        language: system
        args:
          [
            fs,
            --cache-dir,
            tmp/trivy,
            --ignorefile,
            ./.trivyignore.yaml,
            --exit-code,
            "1",
            .,
          ]
        pass_filenames: false
