---
# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: CC0-1.0
#
# Configuration for yamllint CLI tool
#
# See: https://yamllint.readthedocs.io

extends: default

rules:
  braces:
    forbid: false
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: -1
    max-spaces-inside-empty: -1
  document-start: disable
  line-length:
    max: 88
    level: error
