# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#
# Tasks for mkdocs documentation generator:
#
# https://www.mkdocs.org/

version: "3"

silent: true

tasks:
  default:
    cmds:
      - task: serve

  build:
    desc: Build documentation
    cmds:
      - mkdocs build --strict

  clean:
    desc: Delete generated documentation for project
    cmds:
      - for: ["site"]
        cmd: rm -fr {{ .ITEM }}

  serve:
    desc: Run Website for project documentation
    cmds:
      - mkdocs serve
