# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#
# Testing tasks for Python with mypy and pytest:
#
# - mypy: https://www.mypy-lang.org
# - pytest: https://pytest.org
# - pytest-cov: https://pytest-cov.readthedocs.io
# - pytest-randomly: https://pypi.org/project/pytest-randomly/

version: "3"

silent: true

tasks:
  clean:
    desc: Delete generated files for Python testing
    internal: true
    cmds:
      - for: [".coverage", "__pycache__", ".mypy_cache", ".pytest_cache"]
        cmd: rm -fr {{ .ITEM }}

  typehints:
    desc: Run mypy
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - python3 -m mypy . --exclude bin --ignore-missing-imports

  unit:
    desc: Run pytest
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - python3 -m pytest
