# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#
# Project tasks for the Task runner. Version tasks rely on:
#
# - setuptools_scm: https://setuptools-scm.readthedocs.io

version: "3"

silent: true

tasks:
  clean:
    desc: Delete generated files
    cmds:
      - for: ["tmp"]
        cmd: rm -fr {{ .ITEM }}

  version:
    desc: Get current project version
    cmds:
      - "echo {{.PROJECT_VERSION}}"
    vars:
      PROJECT_VERSION:
        sh: python3 -m setuptools_scm
