# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#
# Developer tasks for uv for the Task runner.
#
# See: https://github.com/astral-sh/uv

version: "3"

silent: true

vars:
  PY_DEVELOPER_REQS_IN: "requirements-dev.in"
  PY_DEVELOPER_REQS_TXT: "requirements-dev.in.txt"
  PY_DEVELOPER_VENV: ".venv"

tasks:
  compile:
    desc: Compile Python requirements files
    dir: "{{ .USER_WORKING_DIR }}"
    cmds:
      - for: { var: PY_REQS_IN }
        cmd: uv pip compile -o {{ .ITEM }}.txt -q {{ .ITEM }}
    vars:
      PY_REQS_IN:
        sh: ls requirements-*.in

  create:
    desc: Create Python virtual environment
    dir: "{{ .USER_WORKING_DIR }}"
    cmds:
      - uv venv -q {{ .PY_DEVELOPER_VENV }}

  delete:
    desc: Delete Python virtual environment
    dir: "{{ .USER_WORKING_DIR }}"
    cmds:
      - rm -fr {{ .PY_DEVELOPER_VENV }}

  editable:
    desc: Install as editable to Python virtual environment
    dir: "{{ .USER_WORKING_DIR }}"
    cmds:
      - uv pip install -e .

  sync:
    desc: Sync Python virtual environment with {{ .PY_DEVELOPER_REQS_TXT }}
    dir: "{{ .USER_WORKING_DIR }}"
    cmds:
      - uv pip sync {{ .PY_DEVELOPER_REQS_TXT }}

  update-reqs:
    desc: Update Python requirements files
    internal: true
    dir: "{{ .USER_WORKING_DIR }}"
    cmds:
      - for: { var: PY_REQS_IN }
        cmd: uv pip compile -U -o {{ .ITEM }}.txt -q {{ .ITEM }}
    vars:
      PY_REQS_IN:
        sh: ls requirements-*.in
